name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Build and Push Docker Image'
        run: |
          gcloud builds submit --tag gcr.io/learning-cycle-v2-467610/teaching-cycle-backend ./backend

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy teaching-cycle-backend \
            --image gcr.io/learning-cycle-v2-467610/teaching-cycle-backend \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }},CORS_ORIGINS=https://learning-cycle-v2.web.app,https://learning-cycle-v2.firebaseapp.com,GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
